name: '${project.name}'
main: me.cyberpew.moovr.Moovr
version: '${project.version}'
description: We like to moove it.
author: Cyberpew
dev-url: '${project.url}'

permissions:
    moovr.use:
        description: Allows a user to use a Moovr pad.
        default: op